### ISSUE TITLE
Wersja aktualna oraz deploy

### ISSUE THREAD

**Issue by adinef** [Gnlknmd/guten-tags#1]
Jak wygląda praca? Wejdzie jakiś tag w najbliższym czasie? No i deploy oczywiście też. Pytam dla kolegi.

**Comment by Gnlknmd** [comment]
Aktualna wersja jest na repozytorium, nie mam lokalnych zmian poza tym. Jutro z dużym prawdopodobieństwem będzie deploy, najprawdopdobniej rano. W tej chwili można po prostu tagować zaznaczany tekst przez normalne API przeglądarki do zaznaczania.
